export const SET_INPUT_SEARCH = "INPUT_SEARCH";
export const SET_PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const ADD_PRODUCTS_IN_DETAIL = "PRODUCT_DETAIL";
export const SET_PRODUCTS_LIST_IN_CART = "PRODUCTS_LIST_IN_CART";
export const ADD_PRODUCTS_LIST_IN_CART = "ADD_PRODUCTS_LIST_IN_CART";
export const REMOVE_PRODUCTS_LIST_IN_CART = "REMOVE_PRODUCTS_LIST_IN_CART";
export const CHANGE_QUANTITY_OF_PRODUCTS_LIST_IN_CART =
  "CHANGE_QUANTITY_OF_PRODUCTS_LIST_IN_CART";
export const CALCULATE_TOTAL_PRODUCTS_LIST_IN_CART =
  "CALCULATE_TOTAL_PRODUCTS_LIST_IN_CART";
